name: Java CI with Maven

on:
  push:
    branches: [ "develop/3.6" ]
  pull_request:
    branches: [ "develop/3.6" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@v1
    - name: Build with Maven
      run: mvn license:format clean install --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
