changelog:
  exclude:
    labels:
      - Ignore for release
  categories:
    - title: 'Major Core & Rule Engine'
      labels:
        - 'Major Core'
        - 'Major Rule Engine'
      exclude:
        labels:
          - 'Bug'
    - title: 'Major UI'
      labels:
        - 'Major UI'
      exclude:
        labels:
          - 'Bug'
    - title: 'Major Transport'
      labels:
        - 'Major Transport'
      exclude:
        labels:
          - 'Bug'
    - title: 'Major Edge'
      labels:
        - 'Major Edge'
      exclude:
        labels:
          - 'Bug'
    - title: 'Core & Rule Engine'
      labels:
        - 'Core'
        - 'Rule Engine'
      exclude:
        labels:
          - 'Bug'
    - title: 'UI'
      labels:
        - 'UI'
      exclude:
        labels:
          - 'Bug'
    - title: 'Transport'
      labels:
        - 'Transport'
      exclude:
        labels:
          - 'Bug'
    - title: 'Edge'
      labels:
        - 'Edge'
      exclude:
        labels:
          - 'Bug'
    - title: 'Bug: Core & Rule Engine'
      labels:
        - 'Core'
        - 'Rule Engine'
        - 'Bug'
    - title: 'Bug: UI'
      labels:
        - 'UI'
        - 'Bug'
    - title: 'Bug: Transport'
      labels:
        - 'Transport'
        - 'Bug'
    - title: 'Bug: Edge'
      labels:
        - 'Edge'
        - 'Bug'

