<!--

    SPDX-FileCopyrightText: Copyright ThingsBoard, Inc.
    SPDX-License-Identifier: BUSL-1.1

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.thingsboard</groupId>
        <version>4.4.0.1-SNAPSHOT</version>
        <artifactId>msa</artifactId>
    </parent>

    <groupId>org.thingsboard.msa</groupId>
    <artifactId>integration</artifactId>
    <packaging>pom</packaging>

    <name>ThingsBoard Transport Microservices</name>
    <url>https://thingsboard.io</url>

    <properties>
        <main.dir>${basedir}/../..</main.dir>
        <docker.push-integration-arm-amd-image.phase>none</docker.push-integration-arm-amd-image.phase>
    </properties>

    <modules>
        <module>http</module>
        <module>mqtt</module>
        <module>opc-ua</module>
        <module>azure</module>
        <module>aws</module>
        <module>tcp-udp</module>
        <module>kafka</module>
        <module>apache-pulsar</module>
        <module>rabbitmq</module>
        <module>pubsub</module>
        <module>coap</module>
        <module>tuya</module>
        <module>executor</module>
    </modules>

    <profiles>
        <profile>
            <id>push-integration-docker-amd-arm-images</id>
            <activation>
                <property>
                    <name>push-integration-docker-amd-arm-images</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>push-integration-latest-docker-amd-arm-images</id>
                                <phase>${docker.push-integration-arm-amd-image.phase}</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>docker</executable>
                                    <workingDirectory>${project.build.directory}</workingDirectory>
                                    <arguments>
                                        <argument>buildx</argument>
                                        <argument>build</argument>
                                        <argument>-t</argument>
                                        <argument>${docker.repo}/${docker.name}:latest</argument>
                                        <argument>--platform=linux/amd64,linux/arm64</argument>
                                        <argument>-o</argument>
                                        <argument>type=registry</argument>
                                        <argument>.</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>push-integration-version-docker-amd-arm-images</id>
                                <phase>${docker.push-integration-arm-amd-image.phase}</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>docker</executable>
                                    <workingDirectory>${project.build.directory}</workingDirectory>
                                    <arguments>
                                        <argument>buildx</argument>
                                        <argument>build</argument>
                                        <argument>-t</argument>
                                        <argument>${docker.repo}/${docker.name}:${project.version}</argument>
                                        <argument>--platform=linux/amd64,linux/arm64</argument>
                                        <argument>-o</argument>
                                        <argument>type=registry</argument>
                                        <argument>.</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>push-lts-integration-docker-amd-arm-images</id>
            <activation>
                <property>
                    <name>push-lts-integration-docker-amd-arm-images</name>
                </property>
            </activation>
            <properties>
                <docker.lts.tag>4.4.0-latest</docker.lts.tag>
                <docker.skip.latest.tag>false</docker.skip.latest.tag>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>push-integration-latest-docker-amd-arm-images</id>
                                <phase>${docker.push-integration-arm-amd-image.phase}</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <skip>${docker.skip.latest.tag}</skip>
                                    <executable>docker</executable>
                                    <workingDirectory>${project.build.directory}</workingDirectory>
                                    <arguments>
                                        <argument>buildx</argument>
                                        <argument>build</argument>
                                        <argument>-t</argument>
                                        <argument>${docker.repo}/${docker.name}:latest</argument>
                                        <argument>--platform=linux/amd64,linux/arm64</argument>
                                        <argument>-o</argument>
                                        <argument>type=registry</argument>
                                        <argument>.</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>push-integration-version-docker-amd-arm-images</id>
                                <phase>${docker.push-integration-arm-amd-image.phase}</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>docker</executable>
                                    <workingDirectory>${project.build.directory}</workingDirectory>
                                    <arguments>
                                        <argument>buildx</argument>
                                        <argument>build</argument>
                                        <argument>-t</argument>
                                        <argument>${docker.repo}/${docker.name}:${project.version}</argument>
                                        <argument>--platform=linux/amd64,linux/arm64</argument>
                                        <argument>-o</argument>
                                        <argument>type=registry</argument>
                                        <argument>.</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>push-integration-lts-docker-amd-arm-images</id>
                                <phase>${docker.push-integration-arm-amd-image.phase}</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>docker</executable>
                                    <workingDirectory>${project.build.directory}</workingDirectory>
                                    <arguments>
                                        <argument>buildx</argument>
                                        <argument>build</argument>
                                        <argument>-t</argument>
                                        <argument>${docker.repo}/${docker.name}:${docker.lts.tag}</argument>
                                        <argument>--platform=linux/amd64,linux/arm64</argument>
                                        <argument>-o</argument>
                                        <argument>type=registry</argument>
                                        <argument>.</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
