#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

server:
  # Server bind address
  address: "0.0.0.0"
  # Server bind port
  port: "8090"
thingsboard:
  enableProxy: "false"
  # ThingsBoard node host
  host: "localhost"
  # ThingsBoard node port
  port: "8080"
security:
  headers:
    x-content-type-options:
      enabled: true
    referrer-policy:
      enabled: true
      value: "strict-origin-when-cross-origin"
    x-frame-options:
      enabled: false
      value: "SAMEORIGIN"
    content-security-policy:
      enabled: false
      value: ""
      report-only: false
logger:
  level: "info"
  path: "logs"
  filename: "tb-web-ui-%DATE%.log"
