#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

export NODE_CONFIG_DIR=${pkg.installFolder}/conf
export LOG_FOLDER=${pkg.logFolder}
export NODE_ENV=production
export WEB_FOLDER=${pkg.installFolder}/web