// SPDX-FileCopyrightText: Copyright The Thingsboard Authors
// SPDX-License-Identifier: Apache-2.0
package org.thingsboard.server.common.data.ai.dto;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.v3.oas.annotations.media.Schema;

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        property = "status",
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        visible = true
)
@JsonSubTypes({
        @JsonSubTypes.Type(value = TbChatResponse.Success.class, name = "SUCCESS"),
        @JsonSubTypes.Type(value = TbChatResponse.Failure.class, name = "FAILURE")
})
public sealed interface TbChatResponse permits TbChatResponse.Success, TbChatResponse.Failure {

    @Schema(
            description = "Indicates whether the request was successful or not",
            example = "SUCCESS"
    )
    String getStatus();

    record Success(
            @Schema(description = "The text content generated by the model")
            String generatedContent
    ) implements TbChatResponse {

        @Override
        @Schema(example = "SUCCESS")
        public String getStatus() {
            return "SUCCESS";
        }

    }

    record Failure(
            @Schema(description = "A string containing details about the failure")
            String errorDetails
    ) implements TbChatResponse {

        @Override
        @Schema(example = "FAILURE")
        public String getStatus() {
            return "FAILURE";
        }

    }

}
