FROM eclipse-temurin:17-jdk

RUN apt-get update \
    && apt-get install -y --no-install-recommends postgresql-client curl procps \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/tb/init /data
COPY entrypoint-backend.sh /opt/tb/entrypoint-backend.sh
COPY init/install.sh /opt/tb/init/install.sh
RUN chmod +x /opt/tb/entrypoint-backend.sh /opt/tb/init/install.sh

WORKDIR /opt/tb
EXPOSE 8080 7070 1883 8883 5005
ENTRYPOINT ["/opt/tb/entrypoint-backend.sh"]
