#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

services:
  cassandra:
    volumes:
      - cassandra-volume:/var/lib/cassandra

volumes:
  cassandra-volume:
    external:
      name: ${CASSANDRA_DATA_VOLUME}
