#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

services:
  tb-js-executor:
    env_file:
      - queue-confluent.env
  tb-core1:
    env_file:
      - queue-confluent.env
  tb-core2:
    env_file:
      - queue-confluent.env
  tb-rule-engine1:
    env_file:
      - queue-confluent.env
  tb-rule-engine2:
    env_file:
      - queue-confluent.env
  tb-mqtt-transport1:
    env_file:
      - queue-confluent.env
  tb-mqtt-transport2:
    env_file:
      - queue-confluent.env
  tb-http-transport1:
    env_file:
      - queue-confluent.env
  tb-http-transport2:
    env_file:
      - queue-confluent.env
  tb-coap-transport:
    env_file:
      - queue-confluent.env
  tb-lwm2m-transport:
    env_file:
      - queue-confluent.env
  tb-snmp-transport:
    env_file:
      - queue-confluent.env
  tb-vc-executor1:
    env_file:
      - queue-confluent.env
  tb-vc-executor2:
    env_file:
      - queue-confluent.env
