#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

services:
  tb-core1:
    env_file:
      - tb-core-edqs.env
  tb-core2:
    env_file:
      - tb-core-edqs.env
  tb-rule-engine1:
    env_file:
      - tb-rule-engine-edqs.env
  tb-rule-engine2:
    env_file:
      - tb-rule-engine-edqs.env
  tb-edqs1:
    restart: always
    image: "${DOCKER_REPO}/${EDQS_DOCKER_NAME}:${TB_VERSION}"
    environment:
      TB_SERVICE_ID: tb-edqs1
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-edqs.env
    volumes:
      - ./tb-edqs/conf:/usr/share/tb-edqs/conf
      - ./tb-edqs/log:/var/log/tb-edqs
    ports:
      - "8080"
    depends_on:
      - zookeeper
      - kafka
  tb-edqs2:
    restart: always
    image: "${DOCKER_REPO}/${EDQS_DOCKER_NAME}:${TB_VERSION}"
    environment:
      TB_SERVICE_ID: tb-edqs2
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-edqs.env
    volumes:
      - ./tb-edqs/conf:/usr/share/tb-edqs/conf
      - ./tb-edqs/log:/var/log/tb-edqs
    ports:
      - "8080"
    depends_on:
      - zookeeper
      - kafka
