#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

services:
  tb-edqs1:
    volumes:
      - tb-edqs-log-volume:/var/log/tb-edqs
  tb-edqs2:
    volumes:
      - tb-edqs-log-volume:/var/log/tb-edqs

volumes:
  tb-edqs-log-volume:
    external:
      name: ${TB_EDQS_LOG_VOLUME}
