#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

services:
  # Valkey cluster
  valkey-node-0:
    volumes:
      - valkey-cluster-data-0:/bitnami/valkey/data
  valkey-node-1:
    volumes:
      - valkey-cluster-data-1:/bitnami/valkey/data
  valkey-node-2:
    volumes:
      - valkey-cluster-data-2:/bitnami/valkey/data
  valkey-node-3:
    volumes:
      - valkey-cluster-data-3:/bitnami/valkey/data
  valkey-node-4:
    volumes:
      - valkey-cluster-data-4:/bitnami/valkey/data
  valkey-node-5:
    volumes:
      - valkey-cluster-data-5:/bitnami/valkey/data

volumes:
  valkey-cluster-data-0:
    external:
      name: ${VALKEY_CLUSTER_DATA_VOLUME_0}
  valkey-cluster-data-1:
    external:
      name: ${VALKEY_CLUSTER_DATA_VOLUME_1}
  valkey-cluster-data-2:
    external:
      name: ${VALKEY_CLUSTER_DATA_VOLUME_2}
  valkey-cluster-data-3:
    external:
      name: ${VALKEY_CLUSTER_DATA_VOLUME_3}
  valkey-cluster-data-4:
    external:
      name: ${VALKEY_CLUSTER_DATA_VOLUME_4}
  valkey-cluster-data-5:
    external:
      name: ${VALKEY_CLUSTER_DATA_VOLUME_5}
