#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

services:
  # Valkey sentinel
  # The latest version of Valkey compatible with ThingsBoard is 8.0
  valkey-primary:
    image: 'bitnamilegacy/valkey:8.0'
    volumes:
      - ./tb-node/valkey-sentinel-data-primary:/bitnami/valkey/data
    environment:
      - 'VALKEY_REPLICATION_MODE=primary'
      - 'VALKEY_PASSWORD=thingsboard'

  valkey-replica:
    image: 'bitnamilegacy/valkey:8.0'
    volumes:
      - ./tb-node/valkey-sentinel-data-replica:/bitnami/valkey/data
    environment:
      - 'VALKEY_REPLICATION_MODE=replica'
      - 'VALKEY_PRIMARY_HOST=valkey-primary'
      - 'VALKEY_PRIMARY_PASSWORD=thingsboard'
      - 'VALKEY_PASSWORD=thingsboard'
    depends_on:
      - valkey-primary

  valkey-sentinel:
    image: 'bitnamilegacy/valkey-sentinel:8.0'
    volumes:
      - ./tb-node/valkey-sentinel-data-sentinel:/bitnami/valkey/data
    environment:
      - 'VALKEY_PRIMARY_HOST=valkey-primary'
      - 'VALKEY_MASTER_SET=myprimary'
      - 'VALKEY_SENTINEL_PASSWORD=sentinel'
      - 'VALKEY_PRIMARY_PASSWORD=thingsboard'
    depends_on:
      - valkey-primary
      - valkey-replica

  # ThingsBoard setup to use valkey-sentinel
  tb-core1:
    env_file:
      - cache-valkey-sentinel.env
    depends_on:
      - valkey-sentinel
  tb-core2:
    env_file:
      - cache-valkey-sentinel.env
    depends_on:
      - valkey-sentinel
  tb-rule-engine1:
    env_file:
      - cache-valkey-sentinel.env
    depends_on:
      - valkey-sentinel
  tb-rule-engine2:
    env_file:
      - cache-valkey-sentinel.env
    depends_on:
      - valkey-sentinel
  tb-mqtt-transport1:
    env_file:
      - cache-valkey-sentinel.env
    depends_on:
      - valkey-sentinel
  tb-mqtt-transport2:
    env_file:
      - cache-valkey-sentinel.env
    depends_on:
      - valkey-sentinel
  tb-http-transport1:
    env_file:
      - cache-valkey-sentinel.env
    depends_on:
      - valkey-sentinel
  tb-http-transport2:
    env_file:
      - cache-valkey-sentinel.env
    depends_on:
      - valkey-sentinel
  tb-coap-transport:
    env_file:
      - cache-valkey-sentinel.env
    depends_on:
      - valkey-sentinel
  tb-lwm2m-transport:
    env_file:
      - cache-valkey-sentinel.env
    depends_on:
      - valkey-sentinel
  tb-snmp-transport:
    env_file:
      - cache-valkey-sentinel.env
    depends_on:
      - valkey-sentinel
  tb-vc-executor1:
    env_file:
      - cache-valkey-sentinel.env
    depends_on:
      - valkey-sentinel
  tb-vc-executor2:
    env_file:
      - cache-valkey-sentinel.env
    depends_on:
      - valkey-sentinel
