#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

services:
  postgres:
    restart: always
    image: "postgres:16"
    ports:
    - "5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tb-node/postgres:/var/lib/postgresql/data
  tb-core1:
    env_file:
      - tb-node.postgres.env
    depends_on:
      - postgres
  tb-core2:
    env_file:
      - tb-node.postgres.env
    depends_on:
      - postgres
  tb-rule-engine1:
    env_file:
      - tb-node.postgres.env
    depends_on:
      - postgres
  tb-rule-engine2:
    env_file:
      - tb-node.postgres.env
    depends_on:
      - postgres
