#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

services:
# Valkey standalone
# The latest version of Valkey compatible with ThingsBoard is 8.0
  valkey:
    restart: always
    image: bitnamilegacy/valkey:8.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '6379:6379'
    volumes:
      - ./tb-node/valkey-data:/bitnami/valkey/data

# ThingsBoard setup to use valkey-standalone
  tb-core1:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-core2:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-rule-engine1:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-rule-engine2:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-mqtt-transport1:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-mqtt-transport2:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-http-transport1:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-http-transport2:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-coap-transport:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-lwm2m-transport:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-snmp-transport:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-vc-executor1:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-vc-executor2:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
