#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

services:
  # Valkey sentinel
  valkey-primary:
    volumes:
      - valkey-sentinel-data-primary:/bitnami/valkey/data
  valkey-replica:
    volumes:
      - valkey-sentinel-data-replica:/bitnami/valkey/data
  valkey-sentinel:
    volumes:
      - valkey-sentinel-data-sentinel:/bitnami/valkey/data

volumes:
  valkey-sentinel-data-primary:
    external:
      name: ${VALKEY_SENTINEL_DATA_VOLUME_PRIMARY}
  valkey-sentinel-data-replica:
    external:
      name: ${VALKEY_SENTINEL_DATA_VOLUME_REPLICA}
  valkey-sentinel-data-sentinel:
    external:
      name: ${VALKEY_SENTINEL_DATA_VOLUME_SENTINEL}
