#
# SPDX-FileCopyrightText: Copyright ThingsBoard, Inc.
# SPDX-License-Identifier: BUSL-1.1
#

export NODE_CONFIG_DIR=${pkg.installFolder}/conf
export LOG_FOLDER=${pkg.logFolder}
export NODE_ENV=production
export CHROME_EXECUTABLE=${pkg.installFolder}/chromium/chrome
