{
 "title": "Attributes Cache",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cache Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(attributes_cache_total[1m])",
     "legendFormat": "{{job}} {{result}}"
    }
   ]
  },
  {
   "title": "Summarized Cache Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(attributes_cache_total{result=\"hit\"}[1m]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum (increase(attributes_cache_total{result=\"miss\"}[1m]))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Attributes Cache Hit Ratio %",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100*\n(\n  sum(increase(attributes_cache_total{result=\"hit\"}[1m])) / \n ( \n    sum(increase(attributes_cache_total{result=\"hit\"}[1m]))\n    + sum(increase(attributes_cache_total{result=\"miss\"}[1m]))\n    )\n)",
     "legendFormat": "Hit Ratio, %"
    }
   ]
  }
 ]
}