{
 "title": "Core and JS Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Core Producer",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName) (increase(core_producer_total[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  },
  {
   "title": "Core Starts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName) (increase(core_total[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  },
  {
   "title": "JsInvoke Stats",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName) (increase(jsInvoke_total[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  }
 ]
}