{
 "title": "Rule Engine Latency",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Quantiles Latency, ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, queue, quantile) (ruleEngine_seconds)*1000",
     "legendFormat": "{{queue}} {{job}} Quantile - {{quantile}}, ms"
    }
   ]
  },
  {
   "title": "Max Latency, ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ruleEngine_seconds_max *1000", "legendFormat": "{{queue}} - {{job}}, ms" }
   ]
  },
  {
   "title": "Average by 1m",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(ruleEngine_seconds_sum[1m])  / increase(ruleEngine_seconds_count[1m])) * 1000",
     "legendFormat": "{{queue}} {{job}}"
    }
   ]
  }
 ]
}