{
 "title": "Rule Engine Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "[Main] Rule Engine Queue Stats",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName)(increase(ruleEngine_total{queue=\"Main\"}[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  },
  {
   "title": "[HighPriority] Rule Engine Queue Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName)(increase(ruleEngine_total{queue=\"HighPriority\"}[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  },
  {
   "title": "[SequentialByOriginator] Rule Engine  Queue Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName)(increase(ruleEngine_total{queue=\"SequentialByOriginator\"}[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  }
 ]
}