#
# Copyright © 2016-2024 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM redislabs/redisgears:1.2.5

# Set default environment variables for PostgreSQL connection
ENV PG_DBNAME=thingsboard
ENV PG_USER=postgres
ENV PG_PASSWORD=postgres
ENV PG_HOST=localhost

# # Install PostgreSQL client libraries
# RUN apt-get update && \
#     apt-get install -y libpq-dev
#     apt-get install -y python3-pip libpq-dev && \
#     pip3 install psycopg2-binary

# # Create a virtual environment and install psycopg2 within it
# RUN /var/opt/redislabs/modules/rg/python3_1.2.5/bin/python3 -m venv /var/opt/redislabs/modules/rg/python3_1.2.5/.venv && \
#     /var/opt/redislabs/modules/rg/python3_1.2.5/.venv/bin/pip install --upgrade pip && \
#     /var/opt/redislabs/modules/rg/python3_1.2.5/.venv/bin/pip install psycopg2-binary


#ENV PATH="/var/opt/redislabs/modules/rg/python3_1.2.5/bin:$PATH"

RUN /var/opt/redislabs/modules/rg//python3_1.2.5//bin/python3 -m pip install --upgrade pip

RUN /var/opt/redislabs/modules/rg//python3_1.2.5//bin/python3 -m pip install gears-cli

RUN /var/opt/redislabs/modules/rg//python3_1.2.5//bin/python3 -m pip install psycopg2-binary

RUN /var/opt/redislabs/modules/rg//python3_1.2.5//bin/python3 -m pip install rgsync
#RUN /var/opt/redislabs/modules/rg//python3_1.2.5//bin/python3 -m pip install psycopg2

#RUN pip install gears-cli

#check user and cmd on respective container source
#https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/11/debian-10/Dockerfile
# USER 1001

# Copy RedisGears scripts to the container
COPY write_behind_stream.py /usr/local/redisgear/scripts/
COPY write_behind.py /usr/local/redisgear/scripts/
COPY read_through.py /usr/local/redisgear/scripts/
