<!--

    SPDX-FileCopyrightText: Copyright The Thingsboard Authors
    SPDX-License-Identifier: Apache-2.0

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.thingsboard</groupId>
        <version>4.2.2.5-SNAPSHOT</version>
        <artifactId>thingsboard</artifactId>
    </parent>
    <artifactId>common</artifactId>
    <packaging>pom</packaging>

    <name>Thingsboard Server Commons</name>
    <url>https://thingsboard.io</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <main.dir>${basedir}/..</main.dir>
    </properties>
    <modules>
        <module>data</module>
        <module>proto</module>
        <module>util</module>
        <module>message</module>
        <module>actor</module>
        <module>queue</module>
        <module>transport</module>
        <module>dao-api</module>
        <module>cluster-api</module>
        <module>stats</module>
        <module>cache</module>
        <module>coap-server</module>
        <module>edge-api</module>
        <module>version-control</module>
        <module>script</module>
        <module>edqs</module>
        <module>discovery-api</module>
    </modules>

</project>
