#
# SPDX-FileCopyrightText: Copyright ThingsBoard, Inc.
# SPDX-License-Identifier: BUSL-1.1
#

export NODE_CONFIG_DIR=/usr/share/tb-web-report/conf
export LOG_FOLDER=/var/log/tb-web-report
export NODE_ENV=production
