// SPDX-FileCopyrightText: Copyright ThingsBoard, Inc.
// SPDX-License-Identifier: BUSL-1.1
package org.thingsboard.server.common.data.group;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import org.thingsboard.server.common.data.BaseData;
import org.thingsboard.server.common.data.EdgeUtils;
import org.thingsboard.server.common.data.EntityType;
import org.thingsboard.server.common.data.ExportableNoTenantIdEntity;
import org.thingsboard.server.common.data.HasName;
import org.thingsboard.server.common.data.HasOwnerId;
import org.thingsboard.server.common.data.HasVersion;
import org.thingsboard.server.common.data.id.CustomMenuId;
import org.thingsboard.server.common.data.id.EntityGroupId;
import org.thingsboard.server.common.data.id.EntityId;
import org.thingsboard.server.common.data.validation.Length;
import org.thingsboard.server.common.data.validation.NoXss;

import java.io.Serial;

@Schema
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@JsonIgnoreProperties(ignoreUnknown = true)
public class EntityGroup extends BaseData<EntityGroupId> implements HasName, HasOwnerId, ExportableNoTenantIdEntity<EntityGroupId>, HasVersion {

    @Serial
    private static final long serialVersionUID = 2807349040519543363L;

    public static final EntityType[] groupTypes = new EntityType[]{
            EntityType.USER, EntityType.CUSTOMER, EntityType.DEVICE,
            EntityType.ASSET, EntityType.ENTITY_VIEW, EntityType.EDGE, EntityType.DASHBOARD,
            EntityType.AGENT
    };

    public static final EntityType[] sharableGroupTypes = new EntityType[]{
            EntityType.CUSTOMER, EntityType.DEVICE,
            EntityType.ASSET, EntityType.ENTITY_VIEW, EntityType.DASHBOARD, EntityType.EDGE,
            EntityType.AGENT
    };

    public static final String GROUP_ALL_NAME = "All";
    public static final String GROUP_TENANT_USERS_NAME = "Tenant Users";
    public static final String GROUP_TENANT_ADMINS_NAME = "Tenant Administrators";
    public static final String GROUP_CUSTOMER_USERS_NAME = "Customer Users";
    public static final String GROUP_CUSTOMER_ADMINS_NAME = "Customer Administrators";
    public static final String GROUP_PUBLIC_USERS_NAME = "Public Users";

    public static final String GROUP_EDGE_ALL_STARTS_WITH = "[Edge]";
    public static final String GROUP_EDGE_ALL_ENDS_WITH = "All";
    public static final String GROUP_EDGE_ALL_NAME_PATTERN = GROUP_EDGE_ALL_STARTS_WITH + " %s " + GROUP_EDGE_ALL_ENDS_WITH;
    public static final String GROUP_EDGE_CUSTOMER_ALL_NAME_PATTERN = GROUP_EDGE_ALL_STARTS_WITH + "[%s] %s " + GROUP_EDGE_ALL_ENDS_WITH;
    public static final String SPARKLING_AUTOGENERATED_GROUP_DESCRIPTION = "Autogenerated group for Sparkplug devices";

    @Schema(requiredMode = Schema.RequiredMode.REQUIRED, allowableValues = {"CUSTOMER", "ASSET", "DEVICE", "USER", "ENTITY_VIEW", "DASHBOARD", "EDGE", "AGENT"})
    private EntityType type;

    @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Name of the entity group", example = "Water meters")
    @NoXss
    @Length(fieldName = "name")
    private String name;

    @Schema(description = "JSON object with the owner of the group - Tenant or Customer Id. " +
            "When omitted or null on creation, defaults to the current user's owner (Tenant for tenant admins, Customer for customer users).")
    private EntityId ownerId;

    @NoXss
    @Schema(description = "Additional parameters of the entity group. " +
            "May include: 'description' (string), " +
            "'isPublic' (boolean, whether this group is shared publicly), " +
            "'publicCustomerId' (string, UUID of the public customer associated with this group).",
            example = "{\"description\":\"Water meters group\",\"isPublic\":false}")
    @JsonDeserialize(using = ConfigurationDeserializer.class)
    private JsonNode additionalInfo;

    @Schema(description = "JSON with the configuration for UI components: list of columns, settings, actions, etc ")
    @JsonDeserialize(using = ConfigurationDeserializer.class)
    private JsonNode configuration;

    private EntityGroupId externalId;
    private Long version;

    public EntityGroup(EntityGroupId id) {
        super(id);
    }

    public EntityGroup(EntityGroup entityGroup) {
        super(entityGroup);
        this.type = entityGroup.getType();
        this.name = entityGroup.getName();
        this.ownerId = entityGroup.getOwnerId();
        this.additionalInfo = entityGroup.getAdditionalInfo() != null ? entityGroup.getAdditionalInfo().deepCopy() : null;
        this.configuration = entityGroup.getConfiguration() != null ? entityGroup.getConfiguration().deepCopy() : null;
        this.externalId = entityGroup.getExternalId();
        this.version = entityGroup.getVersion();
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    @JsonProperty(access = JsonProperty.Access.READ_WRITE)
    public EntityId getOwnerId() {
        return ownerId;
    }

    @JsonProperty
    @Schema(description = "Indicates special group 'All' that contains all entities and can't be deleted.")
    public boolean isGroupAll() {
        return GROUP_ALL_NAME.equals(name);
    }

    @JsonProperty
    @Schema(description = "Indicates special edge group 'All' that contains all entities and can't be deleted.",
            accessMode = Schema.AccessMode.READ_ONLY)
    public boolean isEdgeGroupAll() {
        return EdgeUtils.isEdgeGroupAll(name);
    }

    @JsonIgnore
    public boolean isPublic() {
        if (getAdditionalInfo() != null && getAdditionalInfo().has("isPublic")) {
            return getAdditionalInfo().get("isPublic").asBoolean();
        }
        return false;
    }

    @Schema(description = "Timestamp of the entity group creation, in milliseconds", example = "1609459200000", accessMode = Schema.AccessMode.READ_ONLY)
    @Override
    public long getCreatedTime() {
        return super.getCreatedTime();
    }

    @Schema(description = "JSON object with the EntityGroupId Id. " +
            "Specify this field to update the Entity Group. " +
            "Referencing non-existing Entity Group Id will cause error. " +
            "Omit this field to create new Entity Group.")
    @Override
    public EntityGroupId getId() {
        return super.getId();
    }

}
