// SPDX-FileCopyrightText: Copyright ThingsBoard, Inc.
// SPDX-License-Identifier: BUSL-1.1
plugins {
    id 'groovy'
    id 'java-library'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation localGroovy()
    implementation gradleApi()
    implementation 'com.netflix.nebula:gradle-ospackage-plugin:12.1.1'
    implementation 'org.apache.commons:commons-lang3:3.9'
}

buildDir = projectBuildDir
version = projectVersion

compileGroovy {
    destinationDirectory = file("${buildDir}/classes")
}

description 'ThingsBoard packaging plugin for constructing RPM and DEB package files.'
