<!--

    SPDX-FileCopyrightText: Copyright ThingsBoard, Inc.
    SPDX-License-Identifier: BUSL-1.1

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.thingsboard</groupId>
        <version>4.4.0.1-SNAPSHOT</version>
        <artifactId>thingsboard</artifactId>
    </parent>
    <artifactId>packaging</artifactId>
    <packaging>jar</packaging>

    <name>ThingsBoard Packaging Plugin</name>
    <url>https://thingsboard.io</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <main.dir>${basedir}/..</main.dir>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.netflix.nebula</groupId>
            <artifactId>gradle-ospackage-plugin</artifactId>
            <version>12.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>3.0.9</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.gradle</groupId>
            <artifactId>gradle-tooling-api</artifactId>
            <version>7.1.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.gradle</groupId>
            <artifactId>gradle-core</artifactId>
            <version>6.1.1</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.thingsboard</groupId>
                <artifactId>gradle-maven-plugin</artifactId>
                <configuration>
                    <gradleProjectDirectory>${main.dir}/packaging</gradleProjectDirectory>
                    <tasks>
                        <task>build</task>
                    </tasks>
                    <args>
                        <arg>-PprojectBuildDir=${project.build.directory}</arg>
                        <arg>-PprojectVersion=${project.version}</arg>
                    </args>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>invoke</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>repo.gradle.org</id>
            <url>https://repo.gradle.org/gradle/libs-releases-local</url>
        </repository>
    </repositories>
</project>
